rm -rf /export/home/admin/extras/R/R-2.14/R/library//boot
rm -rf /export/home/admin/extras/R/R-2.14/R/library//class
rm -rf /export/home/admin/extras/R/R-2.14/R/library//cluster
rm -rf /export/home/admin/extras/R/R-2.14/R/library//codetools
rm -rf /export/home/admin/extras/R/R-2.14/R/library//foreign
rm -rf /export/home/admin/extras/R/R-2.14/R/library//KernSmooth
rm -rf /export/home/admin/extras/R/R-2.14/R/library//lattice
rm -rf /export/home/admin/extras/R/R-2.14/R/library//MASS
rm -rf /export/home/admin/extras/R/R-2.14/R/library//Matrix
rm -rf /export/home/admin/extras/R/R-2.14/R/library//mgcv
rm -rf /export/home/admin/extras/R/R-2.14/R/library//nlme
rm -rf /export/home/admin/extras/R/R-2.14/R/library//nnet
rm -rf /export/home/admin/extras/R/R-2.14/R/library//rpart
rm -rf /export/home/admin/extras/R/R-2.14/R/library//spatial
rm -rf /export/home/admin/extras/R/R-2.14/R/library//survival
rm -rf /export/home/admin/extras/R/R-2.14/R/library//parallel
rm -rf /export/home/admin/extras/R/R-2.14/R/library//compiler
rm -rf /scratch/lv39/library/boot
rm -rf /scratch/lv39/library/class
rm -rf /scratch/lv39/library/cluster
rm -rf /scratch/lv39/library/codetools
rm -rf /scratch/lv39/library/foreign
rm -rf /scratch/lv39/library/KernSmooth
rm -rf /scratch/lv39/library/lattice
rm -rf /scratch/lv39/library/MASS
rm -rf /scratch/lv39/library/Matrix
rm -rf /scratch/lv39/library/mgcv
rm -rf /scratch/lv39/library/nlme
rm -rf /scratch/lv39/library/nnet
rm -rf /scratch/lv39/library/rpart
rm -rf /scratch/lv39/library/spatial
rm -rf /scratch/lv39/library/survival
rm -rf /scratch/lv39/library/boot
rm -rf /scratch/lv39/library/class
rm -rf /scratch/lv39/library/cluster
rm -rf /scratch/lv39/library/codetools
rm -rf /scratch/lv39/library/foreign
rm -rf /scratch/lv39/library/KernSmooth
rm -rf /scratch/lv39/library/lattice
rm -rf /scratch/lv39/library/MASS
rm -rf /scratch/lv39/library/Matrix
rm -rf /scratch/lv39/library/mgcv
rm -rf /scratch/lv39/library/nlme
rm -rf /scratch/lv39/library/nnet
rm -rf /scratch/lv39/library/rpart
rm -rf /scratch/lv39/library/spatial
rm -rf /scratch/lv39/library/survival
rm -rf /scratch/lv39/library/boot
rm -rf /scratch/lv39/library/class
rm -rf /scratch/lv39/library/cluster
rm -rf /scratch/lv39/library/codetools
rm -rf /scratch/lv39/library/foreign
rm -rf /scratch/lv39/library/KernSmooth
rm -rf /scratch/lv39/library/lattice
rm -rf /scratch/lv39/library/MASS
rm -rf /scratch/lv39/library/Matrix
rm -rf /scratch/lv39/library/mgcv
rm -rf /scratch/lv39/library/nlme
rm -rf /scratch/lv39/library/nnet
rm -rf /scratch/lv39/library/rpart
rm -rf /scratch/lv39/library/spatial
rm -rf /scratch/lv39/library/survival
rm -rf /scratch/lv39/library/boot
rm -rf /scratch/lv39/library/class
rm -rf /scratch/lv39/library/cluster
rm -rf /scratch/lv39/library/codetools
rm -rf /scratch/lv39/library/foreign
rm -rf /scratch/lv39/library/KernSmooth
rm -rf /scratch/lv39/library/lattice
rm -rf /scratch/lv39/library/MASS
rm -rf /scratch/lv39/library/Matrix
rm -rf /scratch/lv39/library/mgcv
rm -rf /scratch/lv39/library/nlme
rm -rf /scratch/lv39/library/nnet
rm -rf /scratch/lv39/library/rpart
rm -rf /scratch/lv39/library/spatial
rm -rf /scratch/lv39/library/survival
rm -rf /scratch/lv39/library/boot
rm -rf /scratch/lv39/library/class
rm -rf /scratch/lv39/library/cluster
rm -rf /scratch/lv39/library/codetools
rm -rf /scratch/lv39/library/foreign
rm -rf /scratch/lv39/library/KernSmooth
rm -rf /scratch/lv39/library/lattice
rm -rf /scratch/lv39/library/MASS
rm -rf /scratch/lv39/library/Matrix
rm -rf /scratch/lv39/library/mgcv
rm -rf /scratch/lv39/library/nlme
rm -rf /scratch/lv39/library/nnet
rm -rf /scratch/lv39/library/rpart
rm -rf /scratch/lv39/library/spatial
rm -rf /scratch/lv39/library/survival
